services:
    app:
        build: .
        container_name: order_service_laravel
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./database/database.sqlite:/var/www/html/database/database.sqlite
        ports:
            - "8000:80"
        depends_on:
            - redis

    redis:
        image: redis:alpine
        container_name: redis_cache
        restart: unless-stopped
        ports:
            - "6379:6379"
