name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v3

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: pdo, pdo_sqlite
          coverage: none

      - name: Instalar Dependências
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Criar Arquivo `.env`
        run: |
          cp .env.example .env
          php artisan key:generate
          touch database/database.sqlite
          chmod 777 database/database.sqlite
          echo "SENTRY_LARAVEL_DSN=${{ secrets.SENTRY_LARAVEL_DSN }}" >> .env
          echo "SENTRY_TRACES_SAMPLE_RATE=${{ secrets.SENTRY_TRACES_SAMPLE_RATE }}" >> .env
          echo "SENTRY_PROFILES_SAMPLE_RATE=${{ secrets.SENTRY_PROFILES_SAMPLE_RATE }}" >> .env

      - name: Rodar Migrations
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan migrate --force

      - name: Rodar Testes
        run: php artisan test
