name: Deploy Laravel na EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v3

      - name: Configurar Chave SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 54.210.171.70 >> ~/.ssh/known_hosts

      - name: Deploy para EC2
        run: |
          ssh ubuntu@54.210.171.70 << 'EOF'
            cd /home/ubuntu/www/order-service
            git pull origin main
            docker-compose down
            docker-compose up -d --build
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:clear
            exit
          EOF
